name: bolt11_decoder
description: A decoder for BOLT11 invoices
homepage: https://github.com/fusion44/dart_bolt11_decoder
repository: https://github.com/fusion44/dart_bolt11_decoder
issue_tracker: https://github.com/fusion44/dart_bolt11_decoder/issues
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bech32: ^0.2.0
  decimal: ^1.3.0
  convert: ^3.0.1
  fixnum: ^1.0.0
  
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.6.0
